FROM python:3.10.10-slim-buster

WORKDIR /cmdb-flask

RUN > /etc/apt/sources.list ; \
    echo "deb https://mirrors.tuna.tsinghua.edu.cn/debian/ buster main contrib non-free" > /etc/apt/sources.list; \
    apt update;  \
    apt install git -y; \
    git clone https://github.com/swxfll/cmdb.git /cmdb-flask; \
    cd api-server/; \
    python -m pip install --upgrade pip -i https://pypi.doubanio.com/simple; \
    pip3 install -r requirements.txt -i https://pypi.doubanio.com/simple; \
    apt remove git -y

WORKDIR /cmdb-flask/api-server

EXPOSE 5000
CMD [ "python3", "-m" , "flask", "run", "--host=0.0.0.0", "--port=5000"]


# https://www.freecodecamp.org/news
# docker rm -f cmdb-flask && docker rmi cmdb-flask
# docker build --tag cmdb-flask .
# docker run -d --name cmdb-flask -p 5000:5000 cmdb-flask




